# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LAS2ENVImet
                                 A QGIS plugin
 Converts LAS/LAZ point clouds into your ENVI-met database, including LAD calculation and A-gs parameterization
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-16
        copyright            : (C) 2026 by Peer Schöneberger
        email                : P.Schoeneberger@geo.uni-mainz.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LAS2ENVImet class from file LAS2ENVImet.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .las2envimet import LAS2ENVImet
    return LAS2ENVImet(iface)
